#!/bin/bash

set -eo pipefail

if [ $# -gt 0 ]; then
    case $1 in
        --clean)
            sudo rm -rf ${HOME}/.local/src/GNOME/
            sudo rm -rf ${HOME}/.local/src/World/
            export CLEAN=1
            ;;
        *)
            echo "Unrecognized argument $1"
            exit 1
            ;;
    esac
fi

[ -z "$GBUILD_MESON_ARGS" ] && export GBUILD_MESON_ARGS="--prefix=/usr"

t1=$(date +%s%N)

N=0
while read line; do
    echo $N
    echo $line
    if [ $N -le 8 ]; then
        {
            N=$((N + 1)) && gbuild $line && N=$((N - 1))
        } &
    else
        sleep 1
    fi
done << EOF
pwithnall/uhttpmock
gtk
gtk-doc
GLib
gobject-introspection
libgdata
glib-networking
gi-docgen
json-glib
librsvg
libdex
libmks
libsoup
jwestman/blueprint-compiler
dconf
gdk-pixbuf
gnome-desktop
gvdb
gsettings-desktop-schemas
gvfs
gcr
pygobject
pango
librsvg
libhandy
libshumate
libgweather
tinysparql
libsoup
vte
glycin
gjs
libpanel
libadwaita
adwaita-icon-theme
gnome-keyring
gnome-session
mutter
gnome-shell
gdm
xdg-desktop-portal-gnome
EOF

wait

exit 0

# GNOME Core
# gbuild GNOME/vala
# gbuild GNOME/xdg-user-dirs-gtk
# gbuild GNOME/libxml2

gbuild GNOME/sushi
gbuild GNOME/loupe
gbuild GNOME/evince
gbuild GNOME/polari
gbuild GNOME/connections
gbuild GNOME/gnome-settings-daemon
gbuild GNOME/gnome-shell-extensions
gbuild GNOME/gnome-control-center
gbuild GNOME/gnome-online-accounts
gbuild GNOME/gnome-remote-desktop
gbuild GNOME/gnome-disk-utility
gbuild GNOME/gnome-text-editor
gbuild GNOME/gnome-tweaks
gbuild GNOME/gnome-software
gbuild GNOME/gnome-calendar
gbuild GNOME/gnome-calculator
gbuild GNOME/gnome-usage
gbuild GNOME/gnome-boxes
gbuild GNOME/gnome-music
gbuild GNOME/gnome-weather
gbuild GNOME/gnome-maps

gbuild GNOME/localsearch
gbuild GNOME/nautilus

# non-core packages
gbuild World/fragments
gbuild World/chatty
gbuild TheEvilSkeleton/refine
gbuild chergert/ptyxis
# gbuild World/fractal

t2=$(date +%s%N)
delta=$(echo "scale=4;($t2-$t1)/1000000000.0" | bc)
echo -e "$(date) -- Built all in ${delta}s\n" | sudo tee -a /var/log/gbuild.log
